#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoLINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VentasLeon")]
	public partial class VentasLeonDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTb_Abastecimiento(Tb_Abastecimiento instance);
    partial void UpdateTb_Abastecimiento(Tb_Abastecimiento instance);
    partial void DeleteTb_Abastecimiento(Tb_Abastecimiento instance);
    partial void InsertTb_Vendedor(Tb_Vendedor instance);
    partial void UpdateTb_Vendedor(Tb_Vendedor instance);
    partial void DeleteTb_Vendedor(Tb_Vendedor instance);
    partial void InsertTb_Cliente(Tb_Cliente instance);
    partial void UpdateTb_Cliente(Tb_Cliente instance);
    partial void DeleteTb_Cliente(Tb_Cliente instance);
    partial void InsertTb_Detalle_Compra(Tb_Detalle_Compra instance);
    partial void UpdateTb_Detalle_Compra(Tb_Detalle_Compra instance);
    partial void DeleteTb_Detalle_Compra(Tb_Detalle_Compra instance);
    partial void InsertTb_Detalle_Factura(Tb_Detalle_Factura instance);
    partial void UpdateTb_Detalle_Factura(Tb_Detalle_Factura instance);
    partial void DeleteTb_Detalle_Factura(Tb_Detalle_Factura instance);
    partial void InsertTb_Distrito(Tb_Distrito instance);
    partial void UpdateTb_Distrito(Tb_Distrito instance);
    partial void DeleteTb_Distrito(Tb_Distrito instance);
    partial void InsertTb_Factura(Tb_Factura instance);
    partial void UpdateTb_Factura(Tb_Factura instance);
    partial void DeleteTb_Factura(Tb_Factura instance);
    partial void InsertTb_Orden_Compra(Tb_Orden_Compra instance);
    partial void UpdateTb_Orden_Compra(Tb_Orden_Compra instance);
    partial void DeleteTb_Orden_Compra(Tb_Orden_Compra instance);
    partial void InsertTb_Producto(Tb_Producto instance);
    partial void UpdateTb_Producto(Tb_Producto instance);
    partial void DeleteTb_Producto(Tb_Producto instance);
    partial void InsertTb_Proveedor(Tb_Proveedor instance);
    partial void UpdateTb_Proveedor(Tb_Proveedor instance);
    partial void DeleteTb_Proveedor(Tb_Proveedor instance);
    #endregion
		
		public VentasLeonDataContext() : 
				base(global::DemoLINQ.Properties.Settings.Default.VentasLeonConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VentasLeonDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VentasLeonDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VentasLeonDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VentasLeonDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tb_Abastecimiento> Tb_Abastecimiento
		{
			get
			{
				return this.GetTable<Tb_Abastecimiento>();
			}
		}
		
		public System.Data.Linq.Table<Tb_Vendedor> Tb_Vendedor
		{
			get
			{
				return this.GetTable<Tb_Vendedor>();
			}
		}
		
		public System.Data.Linq.Table<Tb_Cliente> Tb_Cliente
		{
			get
			{
				return this.GetTable<Tb_Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Tb_Detalle_Compra> Tb_Detalle_Compra
		{
			get
			{
				return this.GetTable<Tb_Detalle_Compra>();
			}
		}
		
		public System.Data.Linq.Table<Tb_Detalle_Factura> Tb_Detalle_Factura
		{
			get
			{
				return this.GetTable<Tb_Detalle_Factura>();
			}
		}
		
		public System.Data.Linq.Table<Tb_Distrito> Tb_Distrito
		{
			get
			{
				return this.GetTable<Tb_Distrito>();
			}
		}
		
		public System.Data.Linq.Table<Tb_Factura> Tb_Factura
		{
			get
			{
				return this.GetTable<Tb_Factura>();
			}
		}
		
		public System.Data.Linq.Table<Tb_Orden_Compra> Tb_Orden_Compra
		{
			get
			{
				return this.GetTable<Tb_Orden_Compra>();
			}
		}
		
		public System.Data.Linq.Table<Tb_Producto> Tb_Producto
		{
			get
			{
				return this.GetTable<Tb_Producto>();
			}
		}
		
		public System.Data.Linq.Table<Tb_Proveedor> Tb_Proveedor
		{
			get
			{
				return this.GetTable<Tb_Proveedor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_Abastecimiento")]
	public partial class Tb_Abastecimiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Cod_prv;
		
		private string _Cod_pro;
		
		private float _Pre_Aba;
		
		private EntityRef<Tb_Producto> _Tb_Producto;
		
		private EntityRef<Tb_Proveedor> _Tb_Proveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCod_prvChanging(string value);
    partial void OnCod_prvChanged();
    partial void OnCod_proChanging(string value);
    partial void OnCod_proChanged();
    partial void OnPre_AbaChanging(float value);
    partial void OnPre_AbaChanged();
    #endregion
		
		public Tb_Abastecimiento()
		{
			this._Tb_Producto = default(EntityRef<Tb_Producto>);
			this._Tb_Proveedor = default(EntityRef<Tb_Proveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_prv", DbType="NVarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Cod_prv
		{
			get
			{
				return this._Cod_prv;
			}
			set
			{
				if ((this._Cod_prv != value))
				{
					if (this._Tb_Proveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCod_prvChanging(value);
					this.SendPropertyChanging();
					this._Cod_prv = value;
					this.SendPropertyChanged("Cod_prv");
					this.OnCod_prvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_pro", DbType="NVarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Cod_pro
		{
			get
			{
				return this._Cod_pro;
			}
			set
			{
				if ((this._Cod_pro != value))
				{
					if (this._Tb_Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCod_proChanging(value);
					this.SendPropertyChanging();
					this._Cod_pro = value;
					this.SendPropertyChanged("Cod_pro");
					this.OnCod_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pre_Aba", DbType="Real NOT NULL")]
		public float Pre_Aba
		{
			get
			{
				return this._Pre_Aba;
			}
			set
			{
				if ((this._Pre_Aba != value))
				{
					this.OnPre_AbaChanging(value);
					this.SendPropertyChanging();
					this._Pre_Aba = value;
					this.SendPropertyChanged("Pre_Aba");
					this.OnPre_AbaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Producto_Tb_Abastecimiento", Storage="_Tb_Producto", ThisKey="Cod_pro", OtherKey="Cod_pro", IsForeignKey=true)]
		public Tb_Producto Tb_Producto
		{
			get
			{
				return this._Tb_Producto.Entity;
			}
			set
			{
				Tb_Producto previousValue = this._Tb_Producto.Entity;
				if (((previousValue != value) 
							|| (this._Tb_Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_Producto.Entity = null;
						previousValue.Tb_Abastecimiento.Remove(this);
					}
					this._Tb_Producto.Entity = value;
					if ((value != null))
					{
						value.Tb_Abastecimiento.Add(this);
						this._Cod_pro = value.Cod_pro;
					}
					else
					{
						this._Cod_pro = default(string);
					}
					this.SendPropertyChanged("Tb_Producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Proveedor_Tb_Abastecimiento", Storage="_Tb_Proveedor", ThisKey="Cod_prv", OtherKey="Cod_prv", IsForeignKey=true)]
		public Tb_Proveedor Tb_Proveedor
		{
			get
			{
				return this._Tb_Proveedor.Entity;
			}
			set
			{
				Tb_Proveedor previousValue = this._Tb_Proveedor.Entity;
				if (((previousValue != value) 
							|| (this._Tb_Proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_Proveedor.Entity = null;
						previousValue.Tb_Abastecimiento.Remove(this);
					}
					this._Tb_Proveedor.Entity = value;
					if ((value != null))
					{
						value.Tb_Abastecimiento.Add(this);
						this._Cod_prv = value.Cod_prv;
					}
					else
					{
						this._Cod_prv = default(string);
					}
					this.SendPropertyChanged("Tb_Proveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_Vendedor")]
	public partial class Tb_Vendedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cod_ven;
		
		private string _nom_ven;
		
		private string _ape_ven;
		
		private System.Nullable<decimal> _sue_ven;
		
		private System.Nullable<System.DateTime> _fec_ing;
		
		private string _tip_ven;
		
		private EntitySet<Tb_Distrito> _Tb_Distrito;
		
		private EntitySet<Tb_Factura> _Tb_Factura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_venChanging(string value);
    partial void Oncod_venChanged();
    partial void Onnom_venChanging(string value);
    partial void Onnom_venChanged();
    partial void Onape_venChanging(string value);
    partial void Onape_venChanged();
    partial void Onsue_venChanging(System.Nullable<decimal> value);
    partial void Onsue_venChanged();
    partial void Onfec_ingChanging(System.Nullable<System.DateTime> value);
    partial void Onfec_ingChanged();
    partial void Ontip_venChanging(string value);
    partial void Ontip_venChanged();
    #endregion
		
		public Tb_Vendedor()
		{
			this._Tb_Distrito = new EntitySet<Tb_Distrito>(new Action<Tb_Distrito>(this.attach_Tb_Distrito), new Action<Tb_Distrito>(this.detach_Tb_Distrito));
			this._Tb_Factura = new EntitySet<Tb_Factura>(new Action<Tb_Factura>(this.attach_Tb_Factura), new Action<Tb_Factura>(this.detach_Tb_Factura));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_ven", DbType="NVarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cod_ven
		{
			get
			{
				return this._cod_ven;
			}
			set
			{
				if ((this._cod_ven != value))
				{
					this.Oncod_venChanging(value);
					this.SendPropertyChanging();
					this._cod_ven = value;
					this.SendPropertyChanged("cod_ven");
					this.Oncod_venChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_ven", DbType="NVarChar(25)")]
		public string nom_ven
		{
			get
			{
				return this._nom_ven;
			}
			set
			{
				if ((this._nom_ven != value))
				{
					this.Onnom_venChanging(value);
					this.SendPropertyChanging();
					this._nom_ven = value;
					this.SendPropertyChanged("nom_ven");
					this.Onnom_venChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ape_ven", DbType="NVarChar(25)")]
		public string ape_ven
		{
			get
			{
				return this._ape_ven;
			}
			set
			{
				if ((this._ape_ven != value))
				{
					this.Onape_venChanging(value);
					this.SendPropertyChanging();
					this._ape_ven = value;
					this.SendPropertyChanged("ape_ven");
					this.Onape_venChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sue_ven", DbType="Money")]
		public System.Nullable<decimal> sue_ven
		{
			get
			{
				return this._sue_ven;
			}
			set
			{
				if ((this._sue_ven != value))
				{
					this.Onsue_venChanging(value);
					this.SendPropertyChanging();
					this._sue_ven = value;
					this.SendPropertyChanged("sue_ven");
					this.Onsue_venChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fec_ing", DbType="DateTime")]
		public System.Nullable<System.DateTime> fec_ing
		{
			get
			{
				return this._fec_ing;
			}
			set
			{
				if ((this._fec_ing != value))
				{
					this.Onfec_ingChanging(value);
					this.SendPropertyChanging();
					this._fec_ing = value;
					this.SendPropertyChanged("fec_ing");
					this.Onfec_ingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tip_ven", DbType="NVarChar(1)")]
		public string tip_ven
		{
			get
			{
				return this._tip_ven;
			}
			set
			{
				if ((this._tip_ven != value))
				{
					this.Ontip_venChanging(value);
					this.SendPropertyChanging();
					this._tip_ven = value;
					this.SendPropertyChanged("tip_ven");
					this.Ontip_venChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Vendedor_Tb_Distrito", Storage="_Tb_Distrito", ThisKey="cod_ven", OtherKey="Cod_ven")]
		public EntitySet<Tb_Distrito> Tb_Distrito
		{
			get
			{
				return this._Tb_Distrito;
			}
			set
			{
				this._Tb_Distrito.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Vendedor_Tb_Factura", Storage="_Tb_Factura", ThisKey="cod_ven", OtherKey="Cod_ven")]
		public EntitySet<Tb_Factura> Tb_Factura
		{
			get
			{
				return this._Tb_Factura;
			}
			set
			{
				this._Tb_Factura.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tb_Distrito(Tb_Distrito entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Vendedor = this;
		}
		
		private void detach_Tb_Distrito(Tb_Distrito entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Vendedor = null;
		}
		
		private void attach_Tb_Factura(Tb_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Vendedor = this;
		}
		
		private void detach_Tb_Factura(Tb_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Vendedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_Cliente")]
	public partial class Tb_Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Cod_cli;
		
		private string _Raz_soc_cli;
		
		private string _Dir_cli;
		
		private string _Tel_cli;
		
		private string _Ruc_cli;
		
		private string _Cod_dis;
		
		private System.DateTime _Fec_reg;
		
		private string _Tip_cli;
		
		private string _Contacto;
		
		private EntitySet<Tb_Factura> _Tb_Factura;
		
		private EntityRef<Tb_Distrito> _Tb_Distrito;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCod_cliChanging(string value);
    partial void OnCod_cliChanged();
    partial void OnRaz_soc_cliChanging(string value);
    partial void OnRaz_soc_cliChanged();
    partial void OnDir_cliChanging(string value);
    partial void OnDir_cliChanged();
    partial void OnTel_cliChanging(string value);
    partial void OnTel_cliChanged();
    partial void OnRuc_cliChanging(string value);
    partial void OnRuc_cliChanged();
    partial void OnCod_disChanging(string value);
    partial void OnCod_disChanged();
    partial void OnFec_regChanging(System.DateTime value);
    partial void OnFec_regChanged();
    partial void OnTip_cliChanging(string value);
    partial void OnTip_cliChanged();
    partial void OnContactoChanging(string value);
    partial void OnContactoChanged();
    #endregion
		
		public Tb_Cliente()
		{
			this._Tb_Factura = new EntitySet<Tb_Factura>(new Action<Tb_Factura>(this.attach_Tb_Factura), new Action<Tb_Factura>(this.detach_Tb_Factura));
			this._Tb_Distrito = default(EntityRef<Tb_Distrito>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_cli", DbType="NVarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Cod_cli
		{
			get
			{
				return this._Cod_cli;
			}
			set
			{
				if ((this._Cod_cli != value))
				{
					this.OnCod_cliChanging(value);
					this.SendPropertyChanging();
					this._Cod_cli = value;
					this.SendPropertyChanged("Cod_cli");
					this.OnCod_cliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Raz_soc_cli", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Raz_soc_cli
		{
			get
			{
				return this._Raz_soc_cli;
			}
			set
			{
				if ((this._Raz_soc_cli != value))
				{
					this.OnRaz_soc_cliChanging(value);
					this.SendPropertyChanging();
					this._Raz_soc_cli = value;
					this.SendPropertyChanged("Raz_soc_cli");
					this.OnRaz_soc_cliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dir_cli", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Dir_cli
		{
			get
			{
				return this._Dir_cli;
			}
			set
			{
				if ((this._Dir_cli != value))
				{
					this.OnDir_cliChanging(value);
					this.SendPropertyChanging();
					this._Dir_cli = value;
					this.SendPropertyChanged("Dir_cli");
					this.OnDir_cliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel_cli", DbType="NVarChar(8)")]
		public string Tel_cli
		{
			get
			{
				return this._Tel_cli;
			}
			set
			{
				if ((this._Tel_cli != value))
				{
					this.OnTel_cliChanging(value);
					this.SendPropertyChanging();
					this._Tel_cli = value;
					this.SendPropertyChanged("Tel_cli");
					this.OnTel_cliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ruc_cli", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string Ruc_cli
		{
			get
			{
				return this._Ruc_cli;
			}
			set
			{
				if ((this._Ruc_cli != value))
				{
					this.OnRuc_cliChanging(value);
					this.SendPropertyChanging();
					this._Ruc_cli = value;
					this.SendPropertyChanged("Ruc_cli");
					this.OnRuc_cliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_dis", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string Cod_dis
		{
			get
			{
				return this._Cod_dis;
			}
			set
			{
				if ((this._Cod_dis != value))
				{
					if (this._Tb_Distrito.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCod_disChanging(value);
					this.SendPropertyChanging();
					this._Cod_dis = value;
					this.SendPropertyChanged("Cod_dis");
					this.OnCod_disChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fec_reg", DbType="DateTime NOT NULL")]
		public System.DateTime Fec_reg
		{
			get
			{
				return this._Fec_reg;
			}
			set
			{
				if ((this._Fec_reg != value))
				{
					this.OnFec_regChanging(value);
					this.SendPropertyChanging();
					this._Fec_reg = value;
					this.SendPropertyChanged("Fec_reg");
					this.OnFec_regChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tip_cli", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string Tip_cli
		{
			get
			{
				return this._Tip_cli;
			}
			set
			{
				if ((this._Tip_cli != value))
				{
					this.OnTip_cliChanging(value);
					this.SendPropertyChanging();
					this._Tip_cli = value;
					this.SendPropertyChanged("Tip_cli");
					this.OnTip_cliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contacto", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Contacto
		{
			get
			{
				return this._Contacto;
			}
			set
			{
				if ((this._Contacto != value))
				{
					this.OnContactoChanging(value);
					this.SendPropertyChanging();
					this._Contacto = value;
					this.SendPropertyChanged("Contacto");
					this.OnContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Cliente_Tb_Factura", Storage="_Tb_Factura", ThisKey="Cod_cli", OtherKey="Cod_cli")]
		public EntitySet<Tb_Factura> Tb_Factura
		{
			get
			{
				return this._Tb_Factura;
			}
			set
			{
				this._Tb_Factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Distrito_Tb_Cliente", Storage="_Tb_Distrito", ThisKey="Cod_dis", OtherKey="Cod_dis", IsForeignKey=true)]
		public Tb_Distrito Tb_Distrito
		{
			get
			{
				return this._Tb_Distrito.Entity;
			}
			set
			{
				Tb_Distrito previousValue = this._Tb_Distrito.Entity;
				if (((previousValue != value) 
							|| (this._Tb_Distrito.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_Distrito.Entity = null;
						previousValue.Tb_Cliente.Remove(this);
					}
					this._Tb_Distrito.Entity = value;
					if ((value != null))
					{
						value.Tb_Cliente.Add(this);
						this._Cod_dis = value.Cod_dis;
					}
					else
					{
						this._Cod_dis = default(string);
					}
					this.SendPropertyChanged("Tb_Distrito");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tb_Factura(Tb_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Cliente = this;
		}
		
		private void detach_Tb_Factura(Tb_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_Detalle_Compra")]
	public partial class Tb_Detalle_Compra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Num_oco;
		
		private string _Cod_pro;
		
		private System.Nullable<int> _Can_ped;
		
		private EntityRef<Tb_Orden_Compra> _Tb_Orden_Compra;
		
		private EntityRef<Tb_Producto> _Tb_Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNum_ocoChanging(string value);
    partial void OnNum_ocoChanged();
    partial void OnCod_proChanging(string value);
    partial void OnCod_proChanged();
    partial void OnCan_pedChanging(System.Nullable<int> value);
    partial void OnCan_pedChanged();
    #endregion
		
		public Tb_Detalle_Compra()
		{
			this._Tb_Orden_Compra = default(EntityRef<Tb_Orden_Compra>);
			this._Tb_Producto = default(EntityRef<Tb_Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_oco", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Num_oco
		{
			get
			{
				return this._Num_oco;
			}
			set
			{
				if ((this._Num_oco != value))
				{
					if (this._Tb_Orden_Compra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNum_ocoChanging(value);
					this.SendPropertyChanging();
					this._Num_oco = value;
					this.SendPropertyChanged("Num_oco");
					this.OnNum_ocoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_pro", DbType="NVarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Cod_pro
		{
			get
			{
				return this._Cod_pro;
			}
			set
			{
				if ((this._Cod_pro != value))
				{
					if (this._Tb_Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCod_proChanging(value);
					this.SendPropertyChanging();
					this._Cod_pro = value;
					this.SendPropertyChanged("Cod_pro");
					this.OnCod_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Can_ped", DbType="Int")]
		public System.Nullable<int> Can_ped
		{
			get
			{
				return this._Can_ped;
			}
			set
			{
				if ((this._Can_ped != value))
				{
					this.OnCan_pedChanging(value);
					this.SendPropertyChanging();
					this._Can_ped = value;
					this.SendPropertyChanged("Can_ped");
					this.OnCan_pedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Orden_Compra_Tb_Detalle_Compra", Storage="_Tb_Orden_Compra", ThisKey="Num_oco", OtherKey="Num_oco", IsForeignKey=true)]
		public Tb_Orden_Compra Tb_Orden_Compra
		{
			get
			{
				return this._Tb_Orden_Compra.Entity;
			}
			set
			{
				Tb_Orden_Compra previousValue = this._Tb_Orden_Compra.Entity;
				if (((previousValue != value) 
							|| (this._Tb_Orden_Compra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_Orden_Compra.Entity = null;
						previousValue.Tb_Detalle_Compra.Remove(this);
					}
					this._Tb_Orden_Compra.Entity = value;
					if ((value != null))
					{
						value.Tb_Detalle_Compra.Add(this);
						this._Num_oco = value.Num_oco;
					}
					else
					{
						this._Num_oco = default(string);
					}
					this.SendPropertyChanged("Tb_Orden_Compra");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Producto_Tb_Detalle_Compra", Storage="_Tb_Producto", ThisKey="Cod_pro", OtherKey="Cod_pro", IsForeignKey=true)]
		public Tb_Producto Tb_Producto
		{
			get
			{
				return this._Tb_Producto.Entity;
			}
			set
			{
				Tb_Producto previousValue = this._Tb_Producto.Entity;
				if (((previousValue != value) 
							|| (this._Tb_Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_Producto.Entity = null;
						previousValue.Tb_Detalle_Compra.Remove(this);
					}
					this._Tb_Producto.Entity = value;
					if ((value != null))
					{
						value.Tb_Detalle_Compra.Add(this);
						this._Cod_pro = value.Cod_pro;
					}
					else
					{
						this._Cod_pro = default(string);
					}
					this.SendPropertyChanged("Tb_Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_Detalle_Factura")]
	public partial class Tb_Detalle_Factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Num_fac;
		
		private string _Cod_pro;
		
		private int _Can_ven;
		
		private float _Pre_ven;
		
		private EntityRef<Tb_Factura> _Tb_Factura;
		
		private EntityRef<Tb_Producto> _Tb_Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNum_facChanging(string value);
    partial void OnNum_facChanged();
    partial void OnCod_proChanging(string value);
    partial void OnCod_proChanged();
    partial void OnCan_venChanging(int value);
    partial void OnCan_venChanged();
    partial void OnPre_venChanging(float value);
    partial void OnPre_venChanged();
    #endregion
		
		public Tb_Detalle_Factura()
		{
			this._Tb_Factura = default(EntityRef<Tb_Factura>);
			this._Tb_Producto = default(EntityRef<Tb_Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_fac", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Num_fac
		{
			get
			{
				return this._Num_fac;
			}
			set
			{
				if ((this._Num_fac != value))
				{
					if (this._Tb_Factura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNum_facChanging(value);
					this.SendPropertyChanging();
					this._Num_fac = value;
					this.SendPropertyChanged("Num_fac");
					this.OnNum_facChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_pro", DbType="NVarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Cod_pro
		{
			get
			{
				return this._Cod_pro;
			}
			set
			{
				if ((this._Cod_pro != value))
				{
					if (this._Tb_Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCod_proChanging(value);
					this.SendPropertyChanging();
					this._Cod_pro = value;
					this.SendPropertyChanged("Cod_pro");
					this.OnCod_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Can_ven", DbType="Int NOT NULL")]
		public int Can_ven
		{
			get
			{
				return this._Can_ven;
			}
			set
			{
				if ((this._Can_ven != value))
				{
					this.OnCan_venChanging(value);
					this.SendPropertyChanging();
					this._Can_ven = value;
					this.SendPropertyChanged("Can_ven");
					this.OnCan_venChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pre_ven", DbType="Real NOT NULL")]
		public float Pre_ven
		{
			get
			{
				return this._Pre_ven;
			}
			set
			{
				if ((this._Pre_ven != value))
				{
					this.OnPre_venChanging(value);
					this.SendPropertyChanging();
					this._Pre_ven = value;
					this.SendPropertyChanged("Pre_ven");
					this.OnPre_venChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Factura_Tb_Detalle_Factura", Storage="_Tb_Factura", ThisKey="Num_fac", OtherKey="Num_fac", IsForeignKey=true)]
		public Tb_Factura Tb_Factura
		{
			get
			{
				return this._Tb_Factura.Entity;
			}
			set
			{
				Tb_Factura previousValue = this._Tb_Factura.Entity;
				if (((previousValue != value) 
							|| (this._Tb_Factura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_Factura.Entity = null;
						previousValue.Tb_Detalle_Factura.Remove(this);
					}
					this._Tb_Factura.Entity = value;
					if ((value != null))
					{
						value.Tb_Detalle_Factura.Add(this);
						this._Num_fac = value.Num_fac;
					}
					else
					{
						this._Num_fac = default(string);
					}
					this.SendPropertyChanged("Tb_Factura");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Producto_Tb_Detalle_Factura", Storage="_Tb_Producto", ThisKey="Cod_pro", OtherKey="Cod_pro", IsForeignKey=true)]
		public Tb_Producto Tb_Producto
		{
			get
			{
				return this._Tb_Producto.Entity;
			}
			set
			{
				Tb_Producto previousValue = this._Tb_Producto.Entity;
				if (((previousValue != value) 
							|| (this._Tb_Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_Producto.Entity = null;
						previousValue.Tb_Detalle_Factura.Remove(this);
					}
					this._Tb_Producto.Entity = value;
					if ((value != null))
					{
						value.Tb_Detalle_Factura.Add(this);
						this._Cod_pro = value.Cod_pro;
					}
					else
					{
						this._Cod_pro = default(string);
					}
					this.SendPropertyChanged("Tb_Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_Distrito")]
	public partial class Tb_Distrito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Cod_dis;
		
		private string _Nom_dis;
		
		private string _Cod_ven;
		
		private EntitySet<Tb_Cliente> _Tb_Cliente;
		
		private EntitySet<Tb_Proveedor> _Tb_Proveedor;
		
		private EntityRef<Tb_Vendedor> _Tb_Vendedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCod_disChanging(string value);
    partial void OnCod_disChanged();
    partial void OnNom_disChanging(string value);
    partial void OnNom_disChanged();
    partial void OnCod_venChanging(string value);
    partial void OnCod_venChanged();
    #endregion
		
		public Tb_Distrito()
		{
			this._Tb_Cliente = new EntitySet<Tb_Cliente>(new Action<Tb_Cliente>(this.attach_Tb_Cliente), new Action<Tb_Cliente>(this.detach_Tb_Cliente));
			this._Tb_Proveedor = new EntitySet<Tb_Proveedor>(new Action<Tb_Proveedor>(this.attach_Tb_Proveedor), new Action<Tb_Proveedor>(this.detach_Tb_Proveedor));
			this._Tb_Vendedor = default(EntityRef<Tb_Vendedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_dis", DbType="NVarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Cod_dis
		{
			get
			{
				return this._Cod_dis;
			}
			set
			{
				if ((this._Cod_dis != value))
				{
					this.OnCod_disChanging(value);
					this.SendPropertyChanging();
					this._Cod_dis = value;
					this.SendPropertyChanged("Cod_dis");
					this.OnCod_disChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_dis", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Nom_dis
		{
			get
			{
				return this._Nom_dis;
			}
			set
			{
				if ((this._Nom_dis != value))
				{
					this.OnNom_disChanging(value);
					this.SendPropertyChanging();
					this._Nom_dis = value;
					this.SendPropertyChanged("Nom_dis");
					this.OnNom_disChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_ven", DbType="NVarChar(3)")]
		public string Cod_ven
		{
			get
			{
				return this._Cod_ven;
			}
			set
			{
				if ((this._Cod_ven != value))
				{
					if (this._Tb_Vendedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCod_venChanging(value);
					this.SendPropertyChanging();
					this._Cod_ven = value;
					this.SendPropertyChanged("Cod_ven");
					this.OnCod_venChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Distrito_Tb_Cliente", Storage="_Tb_Cliente", ThisKey="Cod_dis", OtherKey="Cod_dis")]
		public EntitySet<Tb_Cliente> Tb_Cliente
		{
			get
			{
				return this._Tb_Cliente;
			}
			set
			{
				this._Tb_Cliente.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Distrito_Tb_Proveedor", Storage="_Tb_Proveedor", ThisKey="Cod_dis", OtherKey="Cod_dis")]
		public EntitySet<Tb_Proveedor> Tb_Proveedor
		{
			get
			{
				return this._Tb_Proveedor;
			}
			set
			{
				this._Tb_Proveedor.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Vendedor_Tb_Distrito", Storage="_Tb_Vendedor", ThisKey="Cod_ven", OtherKey="cod_ven", IsForeignKey=true)]
		public Tb_Vendedor Tb_Vendedor
		{
			get
			{
				return this._Tb_Vendedor.Entity;
			}
			set
			{
				Tb_Vendedor previousValue = this._Tb_Vendedor.Entity;
				if (((previousValue != value) 
							|| (this._Tb_Vendedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_Vendedor.Entity = null;
						previousValue.Tb_Distrito.Remove(this);
					}
					this._Tb_Vendedor.Entity = value;
					if ((value != null))
					{
						value.Tb_Distrito.Add(this);
						this._Cod_ven = value.cod_ven;
					}
					else
					{
						this._Cod_ven = default(string);
					}
					this.SendPropertyChanged("Tb_Vendedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tb_Cliente(Tb_Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Distrito = this;
		}
		
		private void detach_Tb_Cliente(Tb_Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Distrito = null;
		}
		
		private void attach_Tb_Proveedor(Tb_Proveedor entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Distrito = this;
		}
		
		private void detach_Tb_Proveedor(Tb_Proveedor entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Distrito = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_Factura")]
	public partial class Tb_Factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Num_fac;
		
		private System.DateTime _Fec_fac;
		
		private string _Cod_cli;
		
		private System.Nullable<System.DateTime> _Fec_can;
		
		private string _Est_fac;
		
		private string _Cod_ven;
		
		private System.Nullable<decimal> _Por_Igv;
		
		private EntitySet<Tb_Detalle_Factura> _Tb_Detalle_Factura;
		
		private EntityRef<Tb_Cliente> _Tb_Cliente;
		
		private EntityRef<Tb_Vendedor> _Tb_Vendedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNum_facChanging(string value);
    partial void OnNum_facChanged();
    partial void OnFec_facChanging(System.DateTime value);
    partial void OnFec_facChanged();
    partial void OnCod_cliChanging(string value);
    partial void OnCod_cliChanged();
    partial void OnFec_canChanging(System.Nullable<System.DateTime> value);
    partial void OnFec_canChanged();
    partial void OnEst_facChanging(string value);
    partial void OnEst_facChanged();
    partial void OnCod_venChanging(string value);
    partial void OnCod_venChanged();
    partial void OnPor_IgvChanging(System.Nullable<decimal> value);
    partial void OnPor_IgvChanged();
    #endregion
		
		public Tb_Factura()
		{
			this._Tb_Detalle_Factura = new EntitySet<Tb_Detalle_Factura>(new Action<Tb_Detalle_Factura>(this.attach_Tb_Detalle_Factura), new Action<Tb_Detalle_Factura>(this.detach_Tb_Detalle_Factura));
			this._Tb_Cliente = default(EntityRef<Tb_Cliente>);
			this._Tb_Vendedor = default(EntityRef<Tb_Vendedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_fac", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Num_fac
		{
			get
			{
				return this._Num_fac;
			}
			set
			{
				if ((this._Num_fac != value))
				{
					this.OnNum_facChanging(value);
					this.SendPropertyChanging();
					this._Num_fac = value;
					this.SendPropertyChanged("Num_fac");
					this.OnNum_facChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fec_fac", DbType="DateTime NOT NULL")]
		public System.DateTime Fec_fac
		{
			get
			{
				return this._Fec_fac;
			}
			set
			{
				if ((this._Fec_fac != value))
				{
					this.OnFec_facChanging(value);
					this.SendPropertyChanging();
					this._Fec_fac = value;
					this.SendPropertyChanged("Fec_fac");
					this.OnFec_facChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_cli", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
		public string Cod_cli
		{
			get
			{
				return this._Cod_cli;
			}
			set
			{
				if ((this._Cod_cli != value))
				{
					if (this._Tb_Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCod_cliChanging(value);
					this.SendPropertyChanging();
					this._Cod_cli = value;
					this.SendPropertyChanged("Cod_cli");
					this.OnCod_cliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fec_can", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fec_can
		{
			get
			{
				return this._Fec_can;
			}
			set
			{
				if ((this._Fec_can != value))
				{
					this.OnFec_canChanging(value);
					this.SendPropertyChanging();
					this._Fec_can = value;
					this.SendPropertyChanged("Fec_can");
					this.OnFec_canChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Est_fac", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Est_fac
		{
			get
			{
				return this._Est_fac;
			}
			set
			{
				if ((this._Est_fac != value))
				{
					this.OnEst_facChanging(value);
					this.SendPropertyChanging();
					this._Est_fac = value;
					this.SendPropertyChanged("Est_fac");
					this.OnEst_facChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_ven", DbType="NVarChar(3)")]
		public string Cod_ven
		{
			get
			{
				return this._Cod_ven;
			}
			set
			{
				if ((this._Cod_ven != value))
				{
					if (this._Tb_Vendedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCod_venChanging(value);
					this.SendPropertyChanging();
					this._Cod_ven = value;
					this.SendPropertyChanged("Cod_ven");
					this.OnCod_venChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Por_Igv", DbType="Money")]
		public System.Nullable<decimal> Por_Igv
		{
			get
			{
				return this._Por_Igv;
			}
			set
			{
				if ((this._Por_Igv != value))
				{
					this.OnPor_IgvChanging(value);
					this.SendPropertyChanging();
					this._Por_Igv = value;
					this.SendPropertyChanged("Por_Igv");
					this.OnPor_IgvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Factura_Tb_Detalle_Factura", Storage="_Tb_Detalle_Factura", ThisKey="Num_fac", OtherKey="Num_fac")]
		public EntitySet<Tb_Detalle_Factura> Tb_Detalle_Factura
		{
			get
			{
				return this._Tb_Detalle_Factura;
			}
			set
			{
				this._Tb_Detalle_Factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Cliente_Tb_Factura", Storage="_Tb_Cliente", ThisKey="Cod_cli", OtherKey="Cod_cli", IsForeignKey=true)]
		public Tb_Cliente Tb_Cliente
		{
			get
			{
				return this._Tb_Cliente.Entity;
			}
			set
			{
				Tb_Cliente previousValue = this._Tb_Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Tb_Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_Cliente.Entity = null;
						previousValue.Tb_Factura.Remove(this);
					}
					this._Tb_Cliente.Entity = value;
					if ((value != null))
					{
						value.Tb_Factura.Add(this);
						this._Cod_cli = value.Cod_cli;
					}
					else
					{
						this._Cod_cli = default(string);
					}
					this.SendPropertyChanged("Tb_Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Vendedor_Tb_Factura", Storage="_Tb_Vendedor", ThisKey="Cod_ven", OtherKey="cod_ven", IsForeignKey=true)]
		public Tb_Vendedor Tb_Vendedor
		{
			get
			{
				return this._Tb_Vendedor.Entity;
			}
			set
			{
				Tb_Vendedor previousValue = this._Tb_Vendedor.Entity;
				if (((previousValue != value) 
							|| (this._Tb_Vendedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_Vendedor.Entity = null;
						previousValue.Tb_Factura.Remove(this);
					}
					this._Tb_Vendedor.Entity = value;
					if ((value != null))
					{
						value.Tb_Factura.Add(this);
						this._Cod_ven = value.cod_ven;
					}
					else
					{
						this._Cod_ven = default(string);
					}
					this.SendPropertyChanged("Tb_Vendedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tb_Detalle_Factura(Tb_Detalle_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Factura = this;
		}
		
		private void detach_Tb_Detalle_Factura(Tb_Detalle_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Factura = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_Orden_Compra")]
	public partial class Tb_Orden_Compra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Num_oco;
		
		private System.DateTime _Fec_oco;
		
		private string _Cod_prv;
		
		private System.Nullable<System.DateTime> _Fec_ate;
		
		private string _Est_oco;
		
		private EntitySet<Tb_Detalle_Compra> _Tb_Detalle_Compra;
		
		private EntityRef<Tb_Proveedor> _Tb_Proveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNum_ocoChanging(string value);
    partial void OnNum_ocoChanged();
    partial void OnFec_ocoChanging(System.DateTime value);
    partial void OnFec_ocoChanged();
    partial void OnCod_prvChanging(string value);
    partial void OnCod_prvChanged();
    partial void OnFec_ateChanging(System.Nullable<System.DateTime> value);
    partial void OnFec_ateChanged();
    partial void OnEst_ocoChanging(string value);
    partial void OnEst_ocoChanged();
    #endregion
		
		public Tb_Orden_Compra()
		{
			this._Tb_Detalle_Compra = new EntitySet<Tb_Detalle_Compra>(new Action<Tb_Detalle_Compra>(this.attach_Tb_Detalle_Compra), new Action<Tb_Detalle_Compra>(this.detach_Tb_Detalle_Compra));
			this._Tb_Proveedor = default(EntityRef<Tb_Proveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_oco", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Num_oco
		{
			get
			{
				return this._Num_oco;
			}
			set
			{
				if ((this._Num_oco != value))
				{
					this.OnNum_ocoChanging(value);
					this.SendPropertyChanging();
					this._Num_oco = value;
					this.SendPropertyChanged("Num_oco");
					this.OnNum_ocoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fec_oco", DbType="DateTime NOT NULL")]
		public System.DateTime Fec_oco
		{
			get
			{
				return this._Fec_oco;
			}
			set
			{
				if ((this._Fec_oco != value))
				{
					this.OnFec_ocoChanging(value);
					this.SendPropertyChanging();
					this._Fec_oco = value;
					this.SendPropertyChanged("Fec_oco");
					this.OnFec_ocoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_prv", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
		public string Cod_prv
		{
			get
			{
				return this._Cod_prv;
			}
			set
			{
				if ((this._Cod_prv != value))
				{
					if (this._Tb_Proveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCod_prvChanging(value);
					this.SendPropertyChanging();
					this._Cod_prv = value;
					this.SendPropertyChanged("Cod_prv");
					this.OnCod_prvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fec_ate", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fec_ate
		{
			get
			{
				return this._Fec_ate;
			}
			set
			{
				if ((this._Fec_ate != value))
				{
					this.OnFec_ateChanging(value);
					this.SendPropertyChanging();
					this._Fec_ate = value;
					this.SendPropertyChanged("Fec_ate");
					this.OnFec_ateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Est_oco", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Est_oco
		{
			get
			{
				return this._Est_oco;
			}
			set
			{
				if ((this._Est_oco != value))
				{
					this.OnEst_ocoChanging(value);
					this.SendPropertyChanging();
					this._Est_oco = value;
					this.SendPropertyChanged("Est_oco");
					this.OnEst_ocoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Orden_Compra_Tb_Detalle_Compra", Storage="_Tb_Detalle_Compra", ThisKey="Num_oco", OtherKey="Num_oco")]
		public EntitySet<Tb_Detalle_Compra> Tb_Detalle_Compra
		{
			get
			{
				return this._Tb_Detalle_Compra;
			}
			set
			{
				this._Tb_Detalle_Compra.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Proveedor_Tb_Orden_Compra", Storage="_Tb_Proveedor", ThisKey="Cod_prv", OtherKey="Cod_prv", IsForeignKey=true)]
		public Tb_Proveedor Tb_Proveedor
		{
			get
			{
				return this._Tb_Proveedor.Entity;
			}
			set
			{
				Tb_Proveedor previousValue = this._Tb_Proveedor.Entity;
				if (((previousValue != value) 
							|| (this._Tb_Proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_Proveedor.Entity = null;
						previousValue.Tb_Orden_Compra.Remove(this);
					}
					this._Tb_Proveedor.Entity = value;
					if ((value != null))
					{
						value.Tb_Orden_Compra.Add(this);
						this._Cod_prv = value.Cod_prv;
					}
					else
					{
						this._Cod_prv = default(string);
					}
					this.SendPropertyChanged("Tb_Proveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tb_Detalle_Compra(Tb_Detalle_Compra entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Orden_Compra = this;
		}
		
		private void detach_Tb_Detalle_Compra(Tb_Detalle_Compra entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Orden_Compra = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_Producto")]
	public partial class Tb_Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Cod_pro;
		
		private string _Des_pro;
		
		private float _Pre_pro;
		
		private int _Stk_act;
		
		private int _Stk_min;
		
		private string _Uni_med;
		
		private string _Lin_pro;
		
		private bool _Importado;
		
		private EntitySet<Tb_Abastecimiento> _Tb_Abastecimiento;
		
		private EntitySet<Tb_Detalle_Compra> _Tb_Detalle_Compra;
		
		private EntitySet<Tb_Detalle_Factura> _Tb_Detalle_Factura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCod_proChanging(string value);
    partial void OnCod_proChanged();
    partial void OnDes_proChanging(string value);
    partial void OnDes_proChanged();
    partial void OnPre_proChanging(float value);
    partial void OnPre_proChanged();
    partial void OnStk_actChanging(int value);
    partial void OnStk_actChanged();
    partial void OnStk_minChanging(int value);
    partial void OnStk_minChanged();
    partial void OnUni_medChanging(string value);
    partial void OnUni_medChanged();
    partial void OnLin_proChanging(string value);
    partial void OnLin_proChanged();
    partial void OnImportadoChanging(bool value);
    partial void OnImportadoChanged();
    #endregion
		
		public Tb_Producto()
		{
			this._Tb_Abastecimiento = new EntitySet<Tb_Abastecimiento>(new Action<Tb_Abastecimiento>(this.attach_Tb_Abastecimiento), new Action<Tb_Abastecimiento>(this.detach_Tb_Abastecimiento));
			this._Tb_Detalle_Compra = new EntitySet<Tb_Detalle_Compra>(new Action<Tb_Detalle_Compra>(this.attach_Tb_Detalle_Compra), new Action<Tb_Detalle_Compra>(this.detach_Tb_Detalle_Compra));
			this._Tb_Detalle_Factura = new EntitySet<Tb_Detalle_Factura>(new Action<Tb_Detalle_Factura>(this.attach_Tb_Detalle_Factura), new Action<Tb_Detalle_Factura>(this.detach_Tb_Detalle_Factura));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_pro", DbType="NVarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Cod_pro
		{
			get
			{
				return this._Cod_pro;
			}
			set
			{
				if ((this._Cod_pro != value))
				{
					this.OnCod_proChanging(value);
					this.SendPropertyChanging();
					this._Cod_pro = value;
					this.SendPropertyChanged("Cod_pro");
					this.OnCod_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Des_pro", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Des_pro
		{
			get
			{
				return this._Des_pro;
			}
			set
			{
				if ((this._Des_pro != value))
				{
					this.OnDes_proChanging(value);
					this.SendPropertyChanging();
					this._Des_pro = value;
					this.SendPropertyChanged("Des_pro");
					this.OnDes_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pre_pro", DbType="Real NOT NULL")]
		public float Pre_pro
		{
			get
			{
				return this._Pre_pro;
			}
			set
			{
				if ((this._Pre_pro != value))
				{
					this.OnPre_proChanging(value);
					this.SendPropertyChanging();
					this._Pre_pro = value;
					this.SendPropertyChanged("Pre_pro");
					this.OnPre_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stk_act", DbType="Int NOT NULL")]
		public int Stk_act
		{
			get
			{
				return this._Stk_act;
			}
			set
			{
				if ((this._Stk_act != value))
				{
					this.OnStk_actChanging(value);
					this.SendPropertyChanging();
					this._Stk_act = value;
					this.SendPropertyChanged("Stk_act");
					this.OnStk_actChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stk_min", DbType="Int NOT NULL")]
		public int Stk_min
		{
			get
			{
				return this._Stk_min;
			}
			set
			{
				if ((this._Stk_min != value))
				{
					this.OnStk_minChanging(value);
					this.SendPropertyChanging();
					this._Stk_min = value;
					this.SendPropertyChanged("Stk_min");
					this.OnStk_minChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uni_med", DbType="NVarChar(3)")]
		public string Uni_med
		{
			get
			{
				return this._Uni_med;
			}
			set
			{
				if ((this._Uni_med != value))
				{
					this.OnUni_medChanging(value);
					this.SendPropertyChanging();
					this._Uni_med = value;
					this.SendPropertyChanged("Uni_med");
					this.OnUni_medChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lin_pro", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string Lin_pro
		{
			get
			{
				return this._Lin_pro;
			}
			set
			{
				if ((this._Lin_pro != value))
				{
					this.OnLin_proChanging(value);
					this.SendPropertyChanging();
					this._Lin_pro = value;
					this.SendPropertyChanged("Lin_pro");
					this.OnLin_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Importado", DbType="Bit NOT NULL")]
		public bool Importado
		{
			get
			{
				return this._Importado;
			}
			set
			{
				if ((this._Importado != value))
				{
					this.OnImportadoChanging(value);
					this.SendPropertyChanging();
					this._Importado = value;
					this.SendPropertyChanged("Importado");
					this.OnImportadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Producto_Tb_Abastecimiento", Storage="_Tb_Abastecimiento", ThisKey="Cod_pro", OtherKey="Cod_pro")]
		public EntitySet<Tb_Abastecimiento> Tb_Abastecimiento
		{
			get
			{
				return this._Tb_Abastecimiento;
			}
			set
			{
				this._Tb_Abastecimiento.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Producto_Tb_Detalle_Compra", Storage="_Tb_Detalle_Compra", ThisKey="Cod_pro", OtherKey="Cod_pro")]
		public EntitySet<Tb_Detalle_Compra> Tb_Detalle_Compra
		{
			get
			{
				return this._Tb_Detalle_Compra;
			}
			set
			{
				this._Tb_Detalle_Compra.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Producto_Tb_Detalle_Factura", Storage="_Tb_Detalle_Factura", ThisKey="Cod_pro", OtherKey="Cod_pro")]
		public EntitySet<Tb_Detalle_Factura> Tb_Detalle_Factura
		{
			get
			{
				return this._Tb_Detalle_Factura;
			}
			set
			{
				this._Tb_Detalle_Factura.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tb_Abastecimiento(Tb_Abastecimiento entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Producto = this;
		}
		
		private void detach_Tb_Abastecimiento(Tb_Abastecimiento entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Producto = null;
		}
		
		private void attach_Tb_Detalle_Compra(Tb_Detalle_Compra entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Producto = this;
		}
		
		private void detach_Tb_Detalle_Compra(Tb_Detalle_Compra entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Producto = null;
		}
		
		private void attach_Tb_Detalle_Factura(Tb_Detalle_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Producto = this;
		}
		
		private void detach_Tb_Detalle_Factura(Tb_Detalle_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_Proveedor")]
	public partial class Tb_Proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Cod_prv;
		
		private string _Raz_soc_prv;
		
		private string _Dir_prv;
		
		private string _Tel_prv;
		
		private string _Cod_dis;
		
		private string _Rep_ven;
		
		private EntitySet<Tb_Abastecimiento> _Tb_Abastecimiento;
		
		private EntitySet<Tb_Orden_Compra> _Tb_Orden_Compra;
		
		private EntityRef<Tb_Distrito> _Tb_Distrito;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCod_prvChanging(string value);
    partial void OnCod_prvChanged();
    partial void OnRaz_soc_prvChanging(string value);
    partial void OnRaz_soc_prvChanged();
    partial void OnDir_prvChanging(string value);
    partial void OnDir_prvChanged();
    partial void OnTel_prvChanging(string value);
    partial void OnTel_prvChanged();
    partial void OnCod_disChanging(string value);
    partial void OnCod_disChanged();
    partial void OnRep_venChanging(string value);
    partial void OnRep_venChanged();
    #endregion
		
		public Tb_Proveedor()
		{
			this._Tb_Abastecimiento = new EntitySet<Tb_Abastecimiento>(new Action<Tb_Abastecimiento>(this.attach_Tb_Abastecimiento), new Action<Tb_Abastecimiento>(this.detach_Tb_Abastecimiento));
			this._Tb_Orden_Compra = new EntitySet<Tb_Orden_Compra>(new Action<Tb_Orden_Compra>(this.attach_Tb_Orden_Compra), new Action<Tb_Orden_Compra>(this.detach_Tb_Orden_Compra));
			this._Tb_Distrito = default(EntityRef<Tb_Distrito>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_prv", DbType="NVarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Cod_prv
		{
			get
			{
				return this._Cod_prv;
			}
			set
			{
				if ((this._Cod_prv != value))
				{
					this.OnCod_prvChanging(value);
					this.SendPropertyChanging();
					this._Cod_prv = value;
					this.SendPropertyChanged("Cod_prv");
					this.OnCod_prvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Raz_soc_prv", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Raz_soc_prv
		{
			get
			{
				return this._Raz_soc_prv;
			}
			set
			{
				if ((this._Raz_soc_prv != value))
				{
					this.OnRaz_soc_prvChanging(value);
					this.SendPropertyChanging();
					this._Raz_soc_prv = value;
					this.SendPropertyChanged("Raz_soc_prv");
					this.OnRaz_soc_prvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dir_prv", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Dir_prv
		{
			get
			{
				return this._Dir_prv;
			}
			set
			{
				if ((this._Dir_prv != value))
				{
					this.OnDir_prvChanging(value);
					this.SendPropertyChanging();
					this._Dir_prv = value;
					this.SendPropertyChanged("Dir_prv");
					this.OnDir_prvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel_prv", DbType="NVarChar(8)")]
		public string Tel_prv
		{
			get
			{
				return this._Tel_prv;
			}
			set
			{
				if ((this._Tel_prv != value))
				{
					this.OnTel_prvChanging(value);
					this.SendPropertyChanging();
					this._Tel_prv = value;
					this.SendPropertyChanged("Tel_prv");
					this.OnTel_prvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_dis", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string Cod_dis
		{
			get
			{
				return this._Cod_dis;
			}
			set
			{
				if ((this._Cod_dis != value))
				{
					if (this._Tb_Distrito.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCod_disChanging(value);
					this.SendPropertyChanging();
					this._Cod_dis = value;
					this.SendPropertyChanged("Cod_dis");
					this.OnCod_disChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rep_ven", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Rep_ven
		{
			get
			{
				return this._Rep_ven;
			}
			set
			{
				if ((this._Rep_ven != value))
				{
					this.OnRep_venChanging(value);
					this.SendPropertyChanging();
					this._Rep_ven = value;
					this.SendPropertyChanged("Rep_ven");
					this.OnRep_venChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Proveedor_Tb_Abastecimiento", Storage="_Tb_Abastecimiento", ThisKey="Cod_prv", OtherKey="Cod_prv")]
		public EntitySet<Tb_Abastecimiento> Tb_Abastecimiento
		{
			get
			{
				return this._Tb_Abastecimiento;
			}
			set
			{
				this._Tb_Abastecimiento.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Proveedor_Tb_Orden_Compra", Storage="_Tb_Orden_Compra", ThisKey="Cod_prv", OtherKey="Cod_prv")]
		public EntitySet<Tb_Orden_Compra> Tb_Orden_Compra
		{
			get
			{
				return this._Tb_Orden_Compra;
			}
			set
			{
				this._Tb_Orden_Compra.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Distrito_Tb_Proveedor", Storage="_Tb_Distrito", ThisKey="Cod_dis", OtherKey="Cod_dis", IsForeignKey=true)]
		public Tb_Distrito Tb_Distrito
		{
			get
			{
				return this._Tb_Distrito.Entity;
			}
			set
			{
				Tb_Distrito previousValue = this._Tb_Distrito.Entity;
				if (((previousValue != value) 
							|| (this._Tb_Distrito.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_Distrito.Entity = null;
						previousValue.Tb_Proveedor.Remove(this);
					}
					this._Tb_Distrito.Entity = value;
					if ((value != null))
					{
						value.Tb_Proveedor.Add(this);
						this._Cod_dis = value.Cod_dis;
					}
					else
					{
						this._Cod_dis = default(string);
					}
					this.SendPropertyChanged("Tb_Distrito");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tb_Abastecimiento(Tb_Abastecimiento entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Proveedor = this;
		}
		
		private void detach_Tb_Abastecimiento(Tb_Abastecimiento entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Proveedor = null;
		}
		
		private void attach_Tb_Orden_Compra(Tb_Orden_Compra entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Proveedor = this;
		}
		
		private void detach_Tb_Orden_Compra(Tb_Orden_Compra entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Proveedor = null;
		}
	}
}
#pragma warning restore 1591
