//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Ventas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Cliente
    {
        public string Cod_cli { get; set; }
        public string Raz_soc_cli { get; set; }
        public string Dir_cli { get; set; }
        public string Tel_cli { get; set; }
        public string Ruc_cli { get; set; }
        public string Cod_dis { get; set; }
        public System.DateTime Fec_reg { get; set; }
        public string Tip_cli { get; set; }
        public string Contacto { get; set; }
    }
}
