//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Ventas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Vendedor
    {
        public string cod_ven { get; set; }
        public string nom_ven { get; set; }
        public string ape_ven { get; set; }
        public Nullable<decimal> sue_ven { get; set; }
        public Nullable<System.DateTime> fec_ing { get; set; }
        public string tip_ven { get; set; }
    }
}
