//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Ventas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class VentasLeonEntities1 : DbContext
    {
        public VentasLeonEntities1()
            : base("name=VentasLeonEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tb_Cliente> Tb_Cliente { get; set; }
        public DbSet<Tb_Vendedor> Tb_Vendedor { get; set; }
        public DbSet<vw_VistaFacturas> vw_VistaFacturas { get; set; }
    
        public virtual ObjectResult<usp_ListarFacturasClienteFechas_Result> usp_ListarFacturasClienteFechas(string codcli, Nullable<System.DateTime> fecini, Nullable<System.DateTime> fecfin)
        {
            var codcliParameter = codcli != null ?
                new ObjectParameter("codcli", codcli) :
                new ObjectParameter("codcli", typeof(string));
    
            var feciniParameter = fecini.HasValue ?
                new ObjectParameter("fecini", fecini) :
                new ObjectParameter("fecini", typeof(System.DateTime));
    
            var fecfinParameter = fecfin.HasValue ?
                new ObjectParameter("fecfin", fecfin) :
                new ObjectParameter("fecfin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarFacturasClienteFechas_Result>("usp_ListarFacturasClienteFechas", codcliParameter, feciniParameter, fecfinParameter);
        }
    
        public virtual ObjectResult<usp_ListarFacturasVendedorFechas_Result> usp_ListarFacturasVendedorFechas(string codven, Nullable<System.DateTime> fecini, Nullable<System.DateTime> fecfin)
        {
            var codvenParameter = codven != null ?
                new ObjectParameter("codven", codven) :
                new ObjectParameter("codven", typeof(string));
    
            var feciniParameter = fecini.HasValue ?
                new ObjectParameter("fecini", fecini) :
                new ObjectParameter("fecini", typeof(System.DateTime));
    
            var fecfinParameter = fecfin.HasValue ?
                new ObjectParameter("fecfin", fecfin) :
                new ObjectParameter("fecfin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarFacturasVendedorFechas_Result>("usp_ListarFacturasVendedorFechas", codvenParameter, feciniParameter, fecfinParameter);
        }
    
        public virtual ObjectResult<usp_ListarFacturasClienteFechas_Result> ListarFacturasClienteFechas(string codcli, Nullable<System.DateTime> fecini, Nullable<System.DateTime> fecfin)
        {
            var codcliParameter = codcli != null ?
                new ObjectParameter("codcli", codcli) :
                new ObjectParameter("codcli", typeof(string));
    
            var feciniParameter = fecini.HasValue ?
                new ObjectParameter("fecini", fecini) :
                new ObjectParameter("fecini", typeof(System.DateTime));
    
            var fecfinParameter = fecfin.HasValue ?
                new ObjectParameter("fecfin", fecfin) :
                new ObjectParameter("fecfin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarFacturasClienteFechas_Result>("ListarFacturasClienteFechas", codcliParameter, feciniParameter, fecfinParameter);
        }
    
        public virtual ObjectResult<usp_ListarFacturasVendedorFechas_Result> ListarFacturasVendedorFechas(string codven, Nullable<System.DateTime> fecini, Nullable<System.DateTime> fecfin)
        {
            var codvenParameter = codven != null ?
                new ObjectParameter("codven", codven) :
                new ObjectParameter("codven", typeof(string));
    
            var feciniParameter = fecini.HasValue ?
                new ObjectParameter("fecini", fecini) :
                new ObjectParameter("fecini", typeof(System.DateTime));
    
            var fecfinParameter = fecfin.HasValue ?
                new ObjectParameter("fecfin", fecfin) :
                new ObjectParameter("fecfin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarFacturasVendedorFechas_Result>("ListarFacturasVendedorFechas", codvenParameter, feciniParameter, fecfinParameter);
        }
    }
}
